theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21
[[block]]

block = "disk_space"
path = "/"
alias = "root"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = true
speed_up = false
speed_down = false
use_bits = false
